name: Meg4 To Bedrock
on: 
  workflow_dispatch:
    inputs:
      file-download-url:
        required: true
        type: string

env:
  file: ${{ inputs.file-download-url }}

jobs:
  Convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install libary
        run: pip install -r requirements.txt
      - name: Convert to Bedrock
        run: python main.py
      - uses: actions/upload-artifact@v4
        with:
          name: Converted
          path: output/